function mh=makeparams(mh)
% Set your intervals
mh.addint('maxtime',10)
mh.addint('iti',0.5)
mh.addint('reward',0.4)

% Set your targets. if doing target logic inside the trial, don't forget to
% add a targ object into your trial structure

mh.addtarg('ball',...
    'position',[0,20;-20,20; 20,20],...
    'size',deg2pix([0.5 0.5],'size'),...
    'color', [0 1 0],...
    'shape','circle', ...
    'speed',20,...
    'direction',270,...
    'degreestype','cart')

mh.addtarg('ball2',...
    'position',[0,20;-20,20; 20,20],...
    'size',deg2pix([0.5 0.5],'size'),...
    'color', [0 1 0],...
    'shape','circle', ...
    'speed',20,...
    'direction',[280;260;230;310],...
    'degreestype','cart')

mh.addtarg('paddle',...
    'position',[0 0],...
    'size',[0 0 177 16],...
    'custompath_x', 'test(mh)',...
    'custompath_y', '700',...
    'degreestype','cart')

%% add walls
mh.addtarg('l_wall',...
    'position',[180,30],...
    'size',[0 0 16 700],...
    'color', [0 1 1],...
    'shape','square')

mh.addtarg('r_wall',...
    'position',[0,30],...
    'size',[0 0 16 700],...
    'color', [0 1 1],...
    'shape','square')

mh.addtarg('t_wall',...
    'position',[90,25],...
    'size',[0 0 700 16],...
    'color', [0 1 1],...
    'shape','square')

mh.addtarg('failwall',...
    'position',[-90,25],...
    'size',[0 0 700 16],...
    'color', [0 1 1],...
    'shape','square')

end