function mh=makeparams(mh)
% Set your intervals
mh.addint('T0_reach',1)
mh.addint('T0_hold',2)
mh.addint('T1_reach',1)
mh.addint('T1_hold',2)
mh.addint('iti',2)
mh.addint('reward',0.2)

% get a picture if you like
image1=imread("assets\Texture1.jpg");
imsizetemp=size(image1);
squareImSize=[0 0 imsizetemp(2)/4 imsizetemp(1)/4];
TEX_1=Screen2('MakeTexture', mh.window_main, image1);

% Set your targets. if doing target logic inside the trial, don't forget to
% add a targ object into your trial structure
center=[mh.xCenter,mh.yCenter];
mh.addtarg('T0',...
    'position',center,...
    'color', [0 1 0],...
    'shape','circle')

mh.addtarg('T1',...
    'position',...
    [100 50; -50 -100; 10 80])

mh.addtarg('T0_moving',...
    'position',center,...
    'speed',0,...
    'direction',[90;0;180;270],...
    'color', [0 1 0],...
    'texture', image1, ...
    'size',squareImSize, ...
    'texture',TEX_1);

mh.addtarg('T1_moving',...
    'position',center,...
    'custompath_x', '(x)+(sin(t)*200)',...
    'custompath_y', '(y)+(sin(t)*100)');


end