function starttrial(mh)
mh.trialstarted = 1;
mh.setstate('start_autogenerated')
mh.evalgraphics('gr.trialstarted=1;');
mh.trial.tstarttime=mh.trial.state.start_autogenerated.time;

mh.autocalibrationmatrix_buffer = mh.autocalibrationmatrix;
xippmex('digout', 4, 1)
for i=1:100
    mh.evalgraphics(['gr.activestatename =' '''' mh.activestatename '''' ';gr.flipped=0;'])
    writeline(mh.graphicsport,'trialstart','0.0.0.0',2023);
    mh.Screen('sendtogr')
    pause(0.001)
end

xippmex('digout', 4, 0);
% [~,~,events]=xippmex('digin');
mh.stimmed=0;
end