function starttrial(mh)
mh.trialstarted = 1;
mh.evalgraphics('gr.trialstarted=1;');
mh.trial.tstarttime=getsecs;
mh.setstate('start_autogenerated')
xippmex('digout', 4, 1)
pause(0.3)
xippmex('digout', 4, 0)
[~,~,events]=xippmex('digin');
end