function stoptrial(mh, success)
mh.setstate('stop_autogenerated')

for i=1:50
    % mh.evalgraphics('gr.trialstarted=0;');
    mh.Screen('FillOval', 'windowPtr', [0 0 0],[8000 8000 8050 8050]);
    mh.Screen('sendtogr')
    % matlabUDP_gandhi('send', mh.graphicsport, 'trialend');   % port 2023, not used
    pause(0.001)
end

% Drain any queued datagrams (replaces flush)
while matlabUDP_gandhi('check', mh.graphicsport)
    matlabUDP_gandhi('receive', mh.graphicsport);
end

mh.graphicssent=1;
mh.trialstarted = 0;
mh.runtrial = 0;
mh.trial.success=success;
if success
    mh.sum_success=mh.sum_success+1;
end
end