%% photodiode diagnostics script
% pull out trials for ez computing
trials=e.trial;

%% check for failed data dumps. (graphics handler dumps data into the trial file at the end of the trial.)
% Check for unrecovered dump info. Basically, data from previous trial is inserted into next.
% Check for unrecovered dump info. Basically, data from previous trial is inserted into next.

count=0;
count2=0;
count3=0;
for i=1:length(trials)
    if isempty(trials(i).data.graphics_fliptimes) || isempty(trials(i).data.DiodeFlipStates)
        count=count+1;
        dumps_failed(count)=i;
    end
    if sum(strcmp(trials(i).data.DiodeFlipStates,'stop_autogenerated'))>1
        count2=count2+1;
        dumps_recovery_failed(count)=i;
    end
    if trials(i).data.photodiode(2)>100
        count3=count3+1;
        photodiode_started_high(count3)=i;
    end
end
clear count count2 count3

%% Check if number of diode flips matches the reported states for which diodes flipped. This excludes failed dumps. 
count=0;
fprintf('\n')
fprintf('%.4f',1/100)
for i=1:length(trials)
    fprintf('\b\b\b\b\b\b')
    fprintf('%.4f',i/length(trials))
    if ~ismember(i,dumps_failed) || ~ismember(i,dumps_recovery_failed)
        numberofstates=length(trials(i).data.DiodeFlipStates);
        flipidx=countflips(trials(i).data.photodiode);
        numberofflips=length(flipidx);
    end

    if numberofstates~=numberofflips
        count=count+1;
        flips_dont_match(count)=i;
    end
end
fprintf('\n')
clear count flipidx
%% functions below here
function out=countflips(in)
out=0;

    % make a fit
    fitted=fit((1:length(in))',in','smoothingspline');
    
    % check if fit crosses 100
    % get starting value. Should be low, but sometimes might be high.
    startval=in(2)>100; % 0 for low, 1 for high

    %iterate to see at what point crossings occur
    count=0;
    for i=1:length(in)
        val=feval(fitted,i);
        if startval == 0
            if val>100
                count=count+1;
                out(count)=i;
                startval=1;
            end
        elseif startval == 1
            if val<100
                count=count+1;
                out(count)=i;
                startval=0;
            end
        end
    end
end
        
