% Set your intervals
mh.addint('T0_Reach',5)
mh.addint('T0_Hold',1)

mh.addint('delay',[0.1:0.05:1.2]);

mh.addint('T1_Reach',2)
mh.addint('T1_Pursuit',0.5)

mh.addint('iti',1.5)
mh.addint('reward',1)

% Set your targets. if doing target logic inside the trial, don't forget to
% add a targ object into your trial structure

mh.addtarg('T0',...
    'position',[0,0],... %position is in theta rho format
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 50,...
    'color', [1 1 1],...
    'shape','circle',...
    'degreestype','cartesian',...
    'custompath_x', 'test(mh,t,x)',...
    'custompath_y', 'test(mh,t,y)');

mh.addtarg('T1_Stationary',...
    'position',[zeros(15,1),(8:22)'],...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 100,...
    'color', [1 1 1],...
    'shape','circle',...
    'degreestype','cartesian');

mh.addtarg('T1_Moving_CCW',...
    'position',[0,0],...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 100,...
    'color', [1 1 1],...
    'shape','circle', ...
    'degreestype','cartesian',...
    'Speed',15,...
    'custompath_x', '(x)+(sin(t)*50)',...
    'custompath_y', '(y)+(cos(t)*50)')

mh.addtarg('T1_Moving_CW',...
    'position',[0,34],...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 100,...
    'color', [1 1 1],...
    'shape','circle', ...
    'degreestype','cartesian',...
    'Speed',15,...
    'custompath_x', '(x)+(sin(t)*50)',...
    'custompath_y', '(y)+(cos(t)*50)')
