% Set your intervals
mh.addint('T0_Reach',5)
mh.addint('T0_Hold',1)

mh.addint('delay',[0.1:0.05:1.2]);

mh.addint('T1_Reach',2)
mh.addint('T1_Hold',0.5)

mh.addint('iti',1.5)
mh.addint('reward',1)

% Set your targets. if doing target logic inside the trial, don't forget to
% add a targ object into your trial structure

mh.addtarg('T0',...
    'position',[0,0],... %position is in theta rho format
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 10,...
    'color', [1 1 1],...
    'shape','circle')

thetapos=rad2deg(-pi:pi/16:pi);
pos=[thetapos', repmat(8,length(thetapos),1)];

mh.addtarg('T1_8deg',...
    'position',pos,...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 10,...
    'color', [1 1 1],...
    'shape','circle',...
    'degreestype','polar');

thetapos=rad2deg(-pi:pi/16:pi);
pos=[thetapos', repmat(10,length(thetapos),1)];

mh.addtarg('T1_10deg',...
    'position',pos,...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 10,...
    'color', [1 1 1],...
    'shape','circle',...
    'degreestype','polar');

thetapos=rad2deg(-pi:pi/16:pi);
pos=[thetapos', repmat(12,length(thetapos),1)];

mh.addtarg('T1_12deg',...
    'position',pos,...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 10,...
    'color', [1 1 1],...
    'shape','circle',...
    'degreestype','polar');


mh.addtarg('T1_Moving_CCW',...
    'position',[0,0],...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 10,...
    'color', [1 1 1],...
    'shape','circle', ...
    'degreestype','cartesian',...
    'speed',15,...
    'custompath_x', '(x)+(sind(t))*10',...
    'custompath_y', '(y)+(cosd(t))*10')

mh.addtarg('T1_Moving_CW',...
    'position',[0,0],...
    'size',deg2pix([0.3 0.3],'size'),...
    'window', 10,...
    'color', [1 1 1],...
    'shape','circle', ...
    'degreestype','cartesian',...
    'speed',15,...
    'custompath_x', '(x)+(sind(t+randi(40)))*10',...
    'custompath_y', '(y)+(cosd(t+randi(40)))*10')
